# Generated by Django 2.2.6 on 2019-12-18 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenModel',
            fields=[
                ('garden_id', models.AutoField(primary_key=True, serialize=False)),
                ('garden_name', models.CharField(max_length=255)),
                ('garden_postalcode', models.IntegerField(default=0)),
                ('garden_coord_lat', models.FloatField(default=0.0)),
                ('garden_coord_lng', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'GardenModel',
            },
        ),
        migrations.CreateModel(
            name='GrowModel',
            fields=[
                ('id_growmodel', models.AutoField(primary_key=True, serialize=False)),
                ('vegfamilyname', models.CharField(max_length=100)),
                ('Kini_days', models.IntegerField(default=0)),
                ('Kdev_days', models.IntegerField(default=0)),
                ('Kmid_days', models.IntegerField(default=0)),
                ('Klate_days', models.IntegerField(default=0)),
                ('Kini', models.FloatField(default=0)),
                ('Kmid', models.FloatField(default=0)),
                ('Kend', models.FloatField(default=0)),
                ('seed_date', models.DateField()),
            ],
            options={
                'db_table': 'GrowModel',
            },
        ),
        migrations.CreateModel(
            name='PixelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_line', models.IntegerField(default=0)),
                ('pixel_col', models.IntegerField(default=0)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('landcov', models.IntegerField(default=0)),
                ('elevation_m', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'PixelModel',
            },
        ),
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id_weather', models.AutoField(primary_key=True, serialize=False)),
                ('sunrise_hr', models.TimeField()),
                ('sunset_hr', models.TimeField()),
                ('temperature', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_force', models.FloatField()),
                ('wind_dir', models.FloatField()),
                ('cloudiness', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=10)),
                ('surface_temperature', models.FloatField()),
                ('surface_temperature_at_10cm', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('precipitation_mm', models.FloatField()),
                ('precipitation_risk', models.FloatField()),
                ('dew_point', models.FloatField()),
                ('id_garden', models.ManyToManyField(to='api.GardenModel')),
            ],
            options={
                'db_table': 'WeatherModel',
            },
        ),
        migrations.CreateModel(
            name='VegetableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_category', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('scient_name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('culture_advice', models.CharField(max_length=100)),
                ('culture_seeding', models.CharField(max_length=100)),
                ('culture_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=100)),
                ('min_max_harvest_month', models.CharField(max_length=100)),
                ('min_max_seed_month_inside', models.CharField(max_length=100)),
                ('min_max_seed_month_outside', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('seeding_advice', models.CharField(max_length=100)),
                ('soil_nature', models.CharField(max_length=100)),
                ('soil_quality', models.CharField(max_length=100)),
                ('sun_expo', models.CharField(max_length=100)),
                ('texture', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('water_need', models.CharField(max_length=100)),
                ('id_growmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.GrowModel')),
            ],
            options={
                'db_table': 'VegetableModel',
            },
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='Pseudo :')),
                ('bio', models.TextField(max_length=500, null=True, verbose_name='Votre biographie :)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='ParcelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_channel', models.IntegerField()),
                ('number_of_plant', models.IntegerField()),
                ('id_vegetable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.VegetableModel')),
            ],
            options={
                'db_table': 'ParcelModel',
            },
        ),
        migrations.CreateModel(
            name='IrrigaiaStatistic',
            fields=[
                ('id_stat', models.AutoField(primary_key=True, serialize=False)),
                ('water_last_hour', models.FloatField(default=0)),
                ('water_last_24hour', models.FloatField(default=0)),
                ('water_last_week', models.FloatField(default=0)),
                ('water_last_month', models.FloatField(default=0)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'IrrigaiaStatistic',
            },
        ),
        migrations.CreateModel(
            name='IrrigaiaDiary',
            fields=[
                ('id_diary', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.IntegerField()),
                ('status', models.BooleanField()),
                ('datetime', models.DateTimeField()),
                ('liters', models.FloatField(default=0.0)),
                ('alarm', models.CharField(max_length=255)),
                ('api_temperature', models.FloatField(default=0.0)),
                ('measured_temp', models.FloatField(default=0.0)),
                ('measured_press', models.FloatField(default=0.0)),
                ('measured_soil_humidity', models.FloatField(default=0.0)),
                ('measured_soil_fertility', models.FloatField(default=0.0)),
                ('measured_luminosity', models.FloatField(default=0.0)),
                ('measured_battery_level', models.FloatField(default=0.0)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'IrrigaiaDiary',
            },
        ),
        migrations.CreateModel(
            name='IrrigaiaDevice',
            fields=[
                ('device_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('device_name', models.CharField(default='irrigaia', max_length=64)),
                ('device_current_alarm', models.CharField(max_length=255)),
                ('device_uptime', models.IntegerField(default=0)),
                ('device_version', models.CharField(max_length=255)),
                ('device_last_time_seen', models.DateTimeField()),
                ('device_settings_wifi_passwd', models.CharField(max_length=12)),
                ('device_settings_wifi_ap', models.CharField(max_length=12)),
                ('device_settings_nb_Of_Channels', models.IntegerField(default=0)),
                ('garden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.GardenModel')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'IrrigaiaDevice',
            },
        ),
        migrations.AddField(
            model_name='gardenmodel',
            name='parcels',
            field=models.ManyToManyField(to='api.ParcelModel'),
        ),
    ]
